# Camera bridge configuration.
# - topic_name: "/camera"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   lazy: true
#   direction: GZ_TO_ROS

# - topic_name: "/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   lazy: true
#   direction: GZ_TO_ROS

# IMU configuration.
- topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  lazy: true
  direction: GZ_TO_ROS

# Magnetometer configuration.
- topic_name: "/magnetometer"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  lazy: true
  direction: GZ_TO_ROS
